'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Namespace DXSample.Properties

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")>
    Friend NotInheritable Partial Class Settings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As DXSample.Properties.Settings = CType((Global.System.Configuration.ApplicationSettingsBase.Synchronized(New DXSample.Properties.Settings())), DXSample.Properties.Settings)

        Public Shared ReadOnly Property [Default] As Settings
            Get
                Return DXSample.Properties.Settings.defaultInstance
            End Get
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute()>
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
        <Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property CultureOverride As String
            Get
                Return(CStr((Me("CultureOverride"))))
            End Get

            Set(ByVal value As String)
                Me("CultureOverride") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute()>
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
        <Global.System.Configuration.DefaultSettingValueAttribute("True")>
        Public Property ShowCultureOverride As Boolean
            Get
                Return(CBool((Me("ShowCultureOverride"))))
            End Get

            Set(ByVal value As Boolean)
                Me("ShowCultureOverride") = value
            End Set
        End Property
    End Class
End Namespace
