'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace My


	<System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
	<System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")>
	Friend NotInheritable Partial Class Settings
		Inherits System.Configuration.ApplicationSettingsBase

		Private Shared defaultInstance As Settings = (CType(System.Configuration.ApplicationSettingsBase.Synchronized(New Settings()), Settings))

		Public Shared ReadOnly Property [Default]() As Settings
			Get
				Return defaultInstance
			End Get
		End Property

		<System.Configuration.UserScopedSettingAttribute()>
		<System.Diagnostics.DebuggerNonUserCodeAttribute()>
		<System.Configuration.DefaultSettingValueAttribute("")>
		Public Property CultureOverride() As String
			Get
				Return (DirectCast(Me("CultureOverride"), String))
			End Get
			Set(ByVal value As String)
				Me("CultureOverride") = value
			End Set
		End Property

		<System.Configuration.UserScopedSettingAttribute()>
		<System.Diagnostics.DebuggerNonUserCodeAttribute()>
		<System.Configuration.DefaultSettingValueAttribute("True")>
		Public Property ShowCultureOverride() As Boolean
			Get
				Return (DirectCast(Me("ShowCultureOverride"), Boolean))
			End Get
			Set(ByVal value As Boolean)
				Me("ShowCultureOverride") = value
			End Set
		End Property
	End Class
End Namespace
